- ignore: {name: Redundant lambda}
- ignore: {name: Use lambda-case}
- ignore: {name: Use tuple-section}
- ignore: {name: Use uncurry}
- ignore: {name: Use <}
- ignore: {name: Use <=<}
- ignore: {name: Use fromMaybe}

- ignore: {name: Use fmap}