name:                iota
version:             0.1.0.0
github:              "cojna/iota"
license:             CC0
author:              "@cojna"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/cojna/iota#readme>

dependencies:
- array
- base
- bytestring
- containers
- deepseq
- time
- hashable
- mtl
- primitive
- split
- unordered-containers
- vector

library:
  source-dirs: src

tests:
  iota-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - iota
    - hspec
    - QuickCheck
