name:                iota
version:             0.1.0.0
github:              "cojna/iota"
license:             OtherLicense
author:              "@cojna"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/cojna/iota/blob/master/README.md>

language: GHC2021

default-extensions:
  - NoImportQualifiedPost

dependencies:
# core
- base
- bytestring
- containers
- deepseq
- mtl
- process
- time
# full
- primitive >= 0.8
- random >= 1.2
- vector >= 0.13

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  iota:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
    dependencies:
      - directory
      - ghc-lib-parser
      - ghc-lib-parser-ex
      - process
      - template-haskell
      - temporary

tests:
  iota-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - iota
    - hspec
    - hspec-core
    - QuickCheck
    - vector

benchmarks:
    iota-benchmark:
        main:            Bench.hs
        source-dirs:     benchmark
        ghc-options:
        - -O2
        - -Wall
        dependencies:
        - iota
        - criterion
        - vector

