version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:latest
    working_directory: /home/stackage
    steps:
      - checkout
      - restore_cache:
          key: cache
      - run: stack test
      - save_cache:
          key: cache
          paths:
            - ~/.stack
            