version: 2
jobs:
    build:
      docker:
          - image: fpco/stack-build:latest
      working_directory: /work
      steps:
          - checkout
          - restore_cache:
              key: package-cache--{{ checksum "package.yaml" }}--{{ checksum "stack.yaml"}}
          - run: stack test
          - save_cache:
              key: package-cache--{{ checksum "package.yaml" }}--{{ checksum "stack.yaml"}}
              paths:
                  - ~/.stack
                  - /work/.stack-work
    build_atcoder:
        docker:
            - image: fpco/stack-build:latest
        working_directory: /work
        environment:
            - STACK_YAML: atcoder.yaml
        steps:
            - checkout
            - restore_cache:
                key: package-cache--{{ checksum "package.yaml" }}--{{ checksum "atcoder.yaml"}}
            - run: stack test
            - save_cache:
                key: package-cache--{{ checksum "package.yaml" }}--{{ checksum "atcoder.yaml"}}
                paths:
                    - ~/.stack
                    - /work/.stack-work
    deploy:
        docker:
            - image: fpco/stack-build:latest
        working_directory: /work
        environment:
            - TARGET_BRANCH: gh-pages
        steps:
            - checkout
            - restore_cache:
                key: package-cache--{{ checksum "package.yaml" }}--{{ checksum "stack.yaml"}}
            - run:
                name: Build documents
                command: |
                    stack haddock
            - add-ssh-keys:
                fingerprints:
                    - 43:ad:28:48:c3:86:23:f6:90:21:09:ba:6d:66:89:74
            - run:
                name: Deploy to GitHub Pages
                command: |
                    git config --global user.name $GIT_USER_NAME
                    git config --global user.email $GIT_USER_EMAIL
                    git clone --depth 1 $CIRCLE_REPOSITORY_URL public
                    cd public
                    git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
                    git rm -rfq .
                    cp -a "../$(stack path --local-doc-root)/." .
                    git add --all
                    git commit -m "Deploy to GitHub Pages: ${CIRCLE_SHA1} [ci skip]"
                    git push --force --quiet origin $TARGET_BRANCH

workflows:
    version: 2
    test_and_deploy:
        jobs:
            - build
            - build_atcoder
            - deploy:
                requires:
                    - build
                    - build_atcoder
                filters:
                    branches:
                        only: master
