version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:latest
    working_directory: /work
    steps:
      - checkout
      - restore_cache:
          key: package-cache--{{ checksum "package.yaml" }}
      - run: stack test
      - save_cache:
          key: package-cache--{{ checksum "package.yaml" }}
          paths:
              - ~/.stack
              - /work/.stack-work
