name: GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Versions
        run: |
          stack --version
          stack ghc -- --version

      - name: Build
        run: stack haddock iota:lib --fast

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./doc

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
